### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by bcldvd** [jianyuan/sveltekit-ai-chatbot#4]
Great job with this template @jianyuan !

However, since the upgrade to Svelte 4, a simple `npm install` fails if one doesn't use --force or --legacy-peer-deps.
I see you're using pnpm now, but the base README still indicate to use npm!

Felt you should know ;)

**Comment by jianyuan** [comment]
Thanks for reporting! I have fixed this in https://github.com/jianyuan/sveltekit-ai-chatbot/commit/55eb5316de02003ced45e1fca347418e8b59bc97.
